'use client';
import {FormEvent,useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import AppShell from '@/components/AppShell';
import {supabase} from '@/lib/supabase';

const ep:any={first_name:'',last_name:'',date_of_birth:'',phone:'',address_line1:'',address_line2:'',city:'',state:'',postal_code:''};
const ee:any={name:'',relationship:'',phone:'',alternate_phone:''};
const em:any={has_medical_conditions:false,allergies:'',medications:'',medical_conditions:'',physical_limitations:'',emergency_notes:'',insurance_company:'',insurance_member_id:'',insurance_group_number:'',insurance_phone:''};
export default function Profile(){
 const router=useRouter();const[uid,setUid]=useState('');const[p,setP]=useState<any>(ep);const[e,setE]=useState<any>(ee);const[m,setM]=useState<any>(em);const[msg,setMsg]=useState('');
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return;}setUid(user.id);const [{data:p0},{data:e0},{data:m0}]=await Promise.all([supabase.from('profiles').select('*').eq('user_id',user.id).maybeSingle(),supabase.from('emergency_contacts').select('*').eq('user_id',user.id).eq('is_primary',true).maybeSingle(),supabase.from('medical_profiles').select('*').eq('user_id',user.id).maybeSingle()]);setP({...ep,...p0});setE({...ee,...e0});setM({...em,...m0});})()},[router]);
 async function save(ev:FormEvent){ev.preventDefault();const {error:a}=await supabase.from('profiles').upsert({...p,user_id:uid});let b:any=null;if(e.id){({error:b}=await supabase.from('emergency_contacts').update({...e,user_id:uid,is_primary:true}).eq('id',e.id))}else{({error:b}=await supabase.from('emergency_contacts').insert({...e,user_id:uid,is_primary:true}))}const {error:c}=await supabase.from('medical_profiles').upsert({...m,user_id:uid});setMsg(a?.message||b?.message||c?.message||'Profile saved.');}
 return <AppShell><div className="eyebrow">My profile</div><h1>Personal record</h1><form className="form" onSubmit={save}><section className="card"><h2>Basic information</h2><div className="row"><F l="First name" v={p.first_name} s={(v)=>setP({...p,first_name:v})}/><F l="Last name" v={p.last_name} s={(v)=>setP({...p,last_name:v})}/><F l="Date of birth" t="date" v={p.date_of_birth} s={(v)=>setP({...p,date_of_birth:v})}/><F l="Phone" v={p.phone} s={(v)=>setP({...p,phone:v})}/></div><F l="Address" v={p.address_line1} s={(v)=>setP({...p,address_line1:v})}/><div className="row"><F l="City" v={p.city} s={(v)=>setP({...p,city:v})}/><F l="State" v={p.state} s={(v)=>setP({...p,state:v})}/></div><F l="ZIP" v={p.postal_code} s={(v)=>setP({...p,postal_code:v})}/></section><section className="card"><h2>Emergency contact</h2><div className="row"><F l="Name" v={e.name} s={(v)=>setE({...e,name:v})}/><F l="Relationship" v={e.relationship} s={(v)=>setE({...e,relationship:v})}/><F l="Phone" v={e.phone} s={(v)=>setE({...e,phone:v})}/><F l="Alternate phone" v={e.alternate_phone} s={(v)=>setE({...e,alternate_phone:v})}/></div></section><section className="card"><h2>Medical information</h2><T l="Allergies" v={m.allergies} s={(v)=>setM({...m,allergies:v})}/><T l="Medications" v={m.medications} s={(v)=>setM({...m,medications:v})}/><T l="Medical conditions" v={m.medical_conditions} s={(v)=>setM({...m,medical_conditions:v})}/><T l="Physical limitations" v={m.physical_limitations} s={(v)=>setM({...m,physical_limitations:v})}/><T l="Emergency notes" v={m.emergency_notes} s={(v)=>setM({...m,emergency_notes:v})}/></section>{msg&&<div className="notice">{msg}</div>}<button className="btn green">Save profile</button></form></AppShell>
}
function F({l,v,s,t='text'}:{l:string,v:any,s:(v:string)=>void,t?:string}){return <div className="field"><label>{l}</label><input type={t} value={v||''} onChange={e=>s(e.target.value)}/></div>}
function T({l,v,s}:{l:string,v:any,s:(v:string)=>void}){return <div className="field"><label>{l}</label><textarea value={v||''} onChange={e=>s(e.target.value)}/></div>}