'use client';
import {FormEvent,useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import AppShell from '@/components/AppShell';
import {supabase} from '@/lib/supabase';
export default function Credentials(){
 const router=useRouter();const[uid,setUid]=useState('');const[types,setTypes]=useState<any[]>([]);const[items,setItems]=useState<any[]>([]);const[msg,setMsg]=useState('');const[form,setForm]=useState<any>({credential_type_id:'',issuing_body:'',credential_number:'',issued_date:'',expires_date:'',file:null,attested:false});
 async function load(id:string){const [{data:t},{data:c}]=await Promise.all([supabase.from('credential_types').select('*').order('name'),supabase.from('credentials').select('*,credential_types(name,renewal_url)').order('created_at',{ascending:false})]);setTypes(t||[]);setItems(c||[]);if(!form.credential_type_id&&t?.[0])setForm((f:any)=>({...f,credential_type_id:t[0].id}));}
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return;}setUid(user.id);await load(user.id)})()},[router]);
 async function add(e:FormEvent){e.preventDefault();if(!form.attested){setMsg('You must certify that this document is authentic and unaltered.');return;}let path=null;if(form.file){const safe=form.file.name.replace(/[^a-zA-Z0-9._-]/g,'_');path=uid+'/'+crypto.randomUUID()+'-'+safe;const {error}=await supabase.storage.from('credential-documents').upload(path,form.file);if(error){setMsg(error.message);return;}}const type=types.find(t=>t.id===form.credential_type_id);const {error}=await supabase.from('credentials').insert({user_id:uid,credential_type_id:form.credential_type_id,issuing_body:form.issuing_body||type?.issuing_body||null,credential_number:form.credential_number||null,issued_date:form.issued_date||null,expires_date:form.expires_date||null,document_path:path,status:'pending',attested_authentic:true,attested_at:new Date().toISOString()});setMsg(error?.message||'Credential submitted.');await load(uid);}
 return <AppShell><div className="eyebrow">Credential wallet</div><h1>Certifications & credentials</h1><div className="grid two"><section className="card"><h2>Your credentials</h2><div className="list">{items.length===0?<p className="muted">No credentials uploaded yet.</p>:items.map(i=><div className="item" key={i.id}><div><strong>{i.credential_types?.name}</strong><div className="muted">{i.expires_date?'Expires '+i.expires_date:'No expiration'} · {i.status}</div></div></div>)}</div></section><section className="card"><h2>Add credential</h2><form className="form" onSubmit={add}><div className="field"><label>Credential type</label><select value={form.credential_type_id} onChange={e=>setForm({...form,credential_type_id:e.target.value})}>{types.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div><div className="field"><label>Issuing organization</label><input value={form.issuing_body} onChange={e=>setForm({...form,issuing_body:e.target.value})}/></div><div className="field"><label>Certificate / ID number</label><input value={form.credential_number} onChange={e=>setForm({...form,credential_number:e.target.value})}/></div><div className="row"><div className="field"><label>Issued date</label><input type="date" value={form.issued_date} onChange={e=>setForm({...form,issued_date:e.target.value})}/></div><div className="field"><label>Expiration date</label><input type="date" value={form.expires_date} onChange={e=>setForm({...form,expires_date:e.target.value})}/></div></div><div className="field"><label>Certificate file</label><input type="file" accept=".pdf,.png,.jpg,.jpeg,.webp" onChange={e=>setForm({...form,file:e.target.files?.[0]||null})}/></div><label><input type="checkbox" checked={form.attested} onChange={e=>setForm({...form,attested:e.target.checked})}/> I certify this document is authentic and unaltered.</label>{msg&&<div className="notice">{msg}</div>}<button className="btn green">Upload credential</button></form></section></div></AppShell>
}